name: Tests
on:
  push:
  workflow_dispatch:
  
jobs:
  Test-Popularity:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Compile solution
        run: javac solutions/Popularity.java
      - name: Test 1
        run: time bash tasks/popularity/run.sh
      - name: Test 2
        run: time bash tasks/popularity/run.sh
      - name: Test 3
        run: time bash tasks/popularity/run.sh
